baseURL = "https://leinxx.github.io/"
title = "Lei's Log"
theme = ["github.com/adityatelange/hugo-PaperMod"]
languageCode = "en-us"
canonifyURLs = true
staticDir = ["static", "assets"]
contentDir = "posts"
buildFuture = true
[permalinks]
  posts = "/posts/:slug/"

[pagination]
  pagerSize = 10

[params]
  env = "production"
  title = "Lei's Log"
  description = "AI, tech, and random stuff"
  author = "Lei Wang"
  defaultTheme = "auto"
  mainSections = ["posts"]
  math = true
  showtoc = true
  tocopen = true
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  comments = false

[params.assets]
  disableHLJS = true

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    attribute = true  #支持对 ![]() 添加 width="xxx"

[markup.highlight]
  guessSyntax = true
  style = "monokai"
  noClasses = false

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
