baseURL = "https://leinxx.github.io/"
title = "Lei's"
theme = ["github.com/adityatelange/hugo-PaperMod"]
languageCode = "en-us"
canonifyURLs = false
relativeURLs = true
staticDir = ["assets"]
contentDir = "contents"
buildFuture = true
[permalinks]
  posts = "/posts/:slug/"

[pagination]
  pagerSize = 10

[params]
  env = "production"
  title = "Lei's"
  description = "AI, tech and random stuff"
  author = "Lei Wang"
  defaultTheme = "auto"
  mainSections = ["posts"]
  math = true
  showtoc = true
  tocopen = true
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  comments = false
  [params.homeInfoParams]
    enabled = false

[params.assets]
  disableHLJS = true
  katex = true

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    attribute = true  #支持对 ![]() 添加 width="xxx"
  [markup.goldmark.extensions.passthrough]
  enable = true

  [markup.goldmark.extensions.passthrough.delimiters]
    block = [["$$","$$"]]
    inline = [["$","$"], ["\\(","\\)"]]

[markup.highlight]
  guessSyntax = true
  style = "monokai"
  noClasses = false

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 30


